language: node_js
node_js:
  - "10"
cache:
  directories:
    - node_modules
services:
  - mongodb
env:
  - DB_URL=mongodb://localhost:27017/test_database
install:
  - npm install
  - npm install -g codecov
notifications:
  email: false
script:
  - npm run coverage
  - codecov -f coverage/*.json
