language: node_js
node_js:
  - "10"
cache:
  directories:
    - node_modules
services:
  - mongodb
install:
  - npm install
  - npm install -g codecov
notifications:
  email: false
script:
  - npm test
  - codecov -f coverage/*.json
