language: node_js
node_js:
  - "10"
cache:
  directories:
    - node_modules
services:
  - mongodb
env:
  global:
    - COIN_TREND_NOTIFIER_DB_URL=mongodb://localhost:27017/test_database
    - COIN_TREND_NOTIFIER_JWT_PRIVATE_KEY=travistravistravis
install:
  - npm install
  - npm install -g codecov
notifications:
  email: false
script:
  - curl $FIREBASE_KEY > src/notifiers/serviceAccountKey.json
  - npm run coverage
  - codecov -f coverage/*.json
deploy:
  skip_cleanup: true
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: coin-trend-notifier-api
