language: node_js
node_js:
  - "10"
cache:
  directories:
    - node_modules
install:
  - npm install -g codecov
  - npm install -g nyc
notifications:
  email: false
script:
  - npm test
  - codecov -f coverage/*.json
